site_name: TA Management Documentation
theme:
  name: material
  logo: ua-logo.svg
  favicon: favicon.png
  palette: 
    scheme: ualberta
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

nav:
    - Admin: index.md
    - Deployment: deployment.md

extra:
  generator: false
  social:
      - icon: fontawesome/solid/globe
        link: https://ua-compsci-ta.ca

markdown_extensions:
  - meta

extra_css:
  - css/extra.css

plugins:
    - search: {}
    - encryptcontent:
        global_password: 4A4W7ygxTtS*%m3h&7b*

copyright: Copyright &copy; 2022 TA Management System, Department of Computing Science
