site_name: TA Management Deployment Documentation
theme:
  name: material
  logo: ua-logo.svg
  favicon: favicon.png
  palette: 
    scheme: ualberta
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.sections
    - toc.integrate
    - navigation.indexes

nav:
    - Frontend: index.md
    - Backend: backend.md

extra:
  generator: false
  social:
      - icon: fontawesome/solid/globe
        link: https://ua-compsci-ta.ca

markdown_extensions:
  - meta

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2022 TA Management System, Department of Computing Science
